# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
