# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20161016_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='adjunto',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='idEstudiante',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nota',
        ),
    ]
