# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20161017_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.Tipo_Proyecto'),
        ),
    ]
