# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_auto_20161017_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('desarrollo', models.CharField(blank=True, max_length=100, null=True)),
                ('adjunto', models.CharField(blank=True, max_length=100, null=True)),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Actividad')),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Estudiante')),
            ],
        ),
    ]
