# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_actividad_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad_estudiante',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
