# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0007_auto_20161011_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_Limite', models.DateField()),
                ('nota', models.IntegerField()),
                ('adjunto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('programa_Consecutivo', models.CharField(max_length=100)),
                ('cod_Programa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('otro_Telefono', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('mail_institucional', models.CharField(max_length=100)),
                ('investigacion', models.CharField(max_length=50)),
                ('nombre_Investigacion_Trabajo_grado', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('rol_Segun_Colciencias', models.CharField(max_length=100)),
                ('nombreMateriaProgramaEstudiante', models.CharField(max_length=100)),
                ('codigoMateriaProgramaEstudiante', models.CharField(max_length=100)),
                ('opcionProyecto1', models.CharField(max_length=100)),
                ('opcionProyecto2', models.CharField(max_length=100)),
                ('opcionProyecto3', models.CharField(max_length=100)),
                ('fecha_Postulacion', models.DateField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Ciclos')),
            ],
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('idFacultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Facultad', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuentes_de_Financiacion',
            fields=[
                ('idFuente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipoFinanciacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_De_Investigacion',
            fields=[
                ('codigo_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_IES', models.CharField(max_length=50)),
                ('nombre_IES', models.CharField(max_length=100)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('fecha_inicio_grupo', models.DateField()),
                ('fecha_vigencia_grupo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lineas_Investigacion',
            fields=[
                ('idLinea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('inscritos', models.CharField(max_length=100)),
                ('finalizados', models.CharField(max_length=100)),
                ('aprobaron', models.CharField(max_length=100)),
                ('cancelaron', models.CharField(max_length=100)),
                ('perdieron', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maximo_Nivel_Educativo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('fecha_Publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo_Basico_Conocimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('nbc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos_de_Investigacion',
            fields=[
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('ano_obtencion_producto', models.CharField(max_length=100)),
                ('mes_obtencion_producto', models.CharField(max_length=100)),
                ('costo_producto', models.FloatField()),
                ('codigo_IES', models.CharField(max_length=100)),
                ('nombre_IES', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('idPrograma', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_programa', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Facultades')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('codigo_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_IES', models.CharField(max_length=100)),
                ('nombreMacroProyecto', models.CharField(max_length=100)),
                ('nombre_IES', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('duracion', models.CharField(max_length=50)),
                ('objetivo_socioeconomico', models.TextField()),
                ('objetivo_proyecto', models.TextField()),
                ('resumen_proyecto', models.TextField()),
                ('resultados_esperados', models.TextField()),
                ('sede', models.CharField(max_length=50)),
                ('nombre_materia', models.CharField(max_length=50)),
                ('codigo_materia', models.CharField(max_length=50)),
                ('grupo_materia', models.CharField(max_length=50)),
                ('horas_asignadas_docente', models.IntegerField()),
                ('gasto_total', models.FloatField()),
                ('tipo_De_gasto', models.CharField(max_length=100)),
                ('valor_semana', models.FloatField()),
                ('sublinea', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('nombreJurados', models.CharField(max_length=100)),
                ('perfiles', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=50)),
                ('realizo_Sustentacion_publica', models.CharField(max_length=50)),
                ('otras_Entidades_Participantes', models.CharField(max_length=50)),
                ('asociado_al_area_de_conocimiento', models.CharField(max_length=50)),
                ('finalizado', models.CharField(max_length=50)),
                ('paz_y_salvo', models.CharField(max_length=50)),
                ('modalidad_de_seminario', models.CharField(max_length=50)),
                ('Fuente_de_financiacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Fuentes_de_Financiacion')),
                ('NBC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Nucleo_Basico_Conocimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Redes_de_Coperacion',
            fields=[
                ('codigo_red', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo_IES', models.CharField(max_length=100)),
                ('nombre_IES', models.CharField(max_length=100)),
                ('fecha_Creacion_Red', models.DateField()),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('crear_Usuarios', models.CharField(max_length=100)),
                ('registrar_Informacion', models.CharField(max_length=100)),
                ('modificar_Informacion', models.CharField(max_length=100)),
                ('eliminar_Informacion', models.CharField(max_length=100)),
                ('crear_Proyecto', models.CharField(max_length=100)),
                ('realizar_Consulta_filtrada', models.CharField(max_length=100)),
                ('adjuntar_archivos', models.CharField(max_length=100)),
                ('enviar_informes', models.CharField(max_length=100)),
                ('asignar_proyecto', models.CharField(max_length=100)),
                ('publicar_Noticias', models.CharField(max_length=100)),
                ('descargar_archivos', models.CharField(max_length=100)),
                ('verProyectosAsignados', models.CharField(max_length=100)),
                ('registrarNota', models.CharField(max_length=100)),
                ('completarInformacionSNIES', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_Participacion_Proyecto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Proyectos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('mail_institucional', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
                ('nro_Proyectos_a_Cargo', models.IntegerField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Roles')),
            ],
        ),
        migrations.AddField(
            model_name='proyectos',
            name='directorDeProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Usuarios'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='idGrupo_investigacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Grupos_De_Investigacion'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='id_lineas_investigacion_asociadas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Lineas_Investigacion'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='maximo_nivel_educativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Maximo_Nivel_Educativo'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='red_investigacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Redes_de_Coperacion'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo_participacion_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.tipo_Participacion_Proyecto'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Tipos_Proyectos'),
        ),
        migrations.AddField(
            model_name='productos_de_investigacion',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Proyectos'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='idPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Usuarios'),
        ),
        migrations.AddField(
            model_name='facultades',
            name='idSede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Sedes'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Facultades'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Programas'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Proyectos'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='idDirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Usuarios'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='idEstudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Estudiantes'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Proyectos'),
        ),
    ]
